spring:
  datasource:
    url: jdbc:mysql://db1.cpbaiimaqaar.ap-northeast-2.rds.amazonaws.com:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true